# MuJoCo ROS control
robot_joints:
  - robot0_joint1
  - robot0_joint2
  - robot0_joint3
  - robot0_joint4
  - robot0_joint5
  - robot0_joint6
  - robot0_joint7

  - gripper0_finger_joint1
  - gripper0_finger_joint2

robot_initial_state:
  # home
  # robot0_shoulder_pan_joint: 0.0
  # robot0_shoulder_lift_joint: 0.0
  # robot0_elbow_joint: 0.0
  # robot0_wrist_1_joint: 0.0
  # robot0_wrist_2_joint: 0.0
  # robot0_wrist_3_joint: 0.0

  # up
  # robot0_shoulder_pan_joint: 0.0
  # robot0_shoulder_lift_joint: -1.5708
  # robot0_elbow_joint: 1.5708
  # robot0_wrist_1_joint: 0.0
  # robot0_wrist_2_joint: 0.0
  # robot0_wrist_3_joint: 0.0

  # side
  # robot0_shoulder_pan_joint: 0.8 
  # robot0_shoulder_lift_joint: 1.347
  # robot0_elbow_joint: -1.195
  # robot0_wrist_1_joint: -1.584
  # robot0_wrist_2_joint: -1.726
  # robot0_wrist_3_joint: 1.830

  # top down
  # -0.470, -1.735, 2.480, -2.275, -1.590, -0.420
  # ["shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint", 
  #  "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"]
  robot0_joint1: 0.0
  robot0_joint2: 0.0
  robot0_joint3: 0.0
  robot0_joint4: 0.0
  robot0_joint5: 0.0
  robot0_joint6: 0.0

  # gripper: [-0.026 -0.267 -0.2   -0.026 -0.267 -0.2  ]
  gripper0_finger_joint1: 0.0
  gripper0_finger_joint2: 0.0
