# load the internal joint trajectory controller, and the custom robot state controller

position_joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot0_joint1
    - robot0_joint2
    - robot0_joint3
    - robot0_joint4
    - robot0_joint5
    - robot0_joint6
    - robot0_joint7
  constraints:
    goal_time: 0.5
    robot0_joint1:
      goal: 0.05
    robot0_joint2:
      goal: 0.05
    robot0_joint3:
      goal: 0.05
    robot0_joint4:
      goal: 0.05
    robot0_joint5:
      goal: 0.05
    robot0_joint6:
      goal: 0.05
    robot0_joint7:
      goal: 0.05

franka_ros_interface:
  custom_franka_state_controller:
    type: franka_interface/CustomFrankaStateController
    publish_rate: 1000  # [Hz]
    joint_names:
      - robot0_joint1
      - robot0_joint2
      - robot0_joint3
      - robot0_joint4
      - robot0_joint5
      - robot0_joint6
      - robot0_joint7
    arm_id: robot0
