mujoco_ros_control/pid_gains:
  robot0_shoulder_pan_joint: {p: 5000.0, i: 0.01, d: 180.0, i_clamp: 1.0}
  robot0_shoulder_lift_joint: {p: 48000.0, i: 0.0, d: 200.0, i_clamp: 1.0}
  robot0_elbow_joint: {p: 48000.0, i: 0.0, d: 5.0, i_clamp: 1.0}
  robot0_wrist_1_joint: {p: 4500.0, i: 0.0, d: 0.0, i_clamp: 1.0}
  robot0_wrist_2_joint: {p: 4000.0, i: 0.1, d: 2.0, i_clamp: 1.0}
  robot0_wrist_3_joint: {p: 450.0, i: 0.0, d: 0.5, i_clamp: 1.0}
  
  # robot0_shoulder_pan_joint: {p: 3000.0, i: 0.0, d: 300.0}
  # robot0_shoulder_lift_joint: {p: 12000.0, i: 100.0, d: 800.0}
  # robot0_elbow_joint: {p: 8000.0, i: 0.0, d: 30.0}
  # robot0_wrist_1_joint: {p: 2000.0, i: 0.0, d: 0.0}
  # robot0_wrist_2_joint: {p: 1900.0, i: 0.0, d: 0.0}
  # robot0_wrist_3_joint: {p: 400.0, i: 0.0, d: 0.0}
