panda_manipulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot0_joint1
    - robot0_joint2
    - robot0_joint3
    - robot0_joint4
    - robot0_joint5
    - robot0_joint6
    - robot0_joint7
  constraints:
    goal_time: 0.6 # 0.6
    stopped_velocity_tolerance: 0.1 # 0.05
    robot0_joint1: {trajectory: 0.1, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
    robot0_joint2: {trajectory: 0.1, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
    robot0_joint3: {trajectory: 0.1, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
    robot0_joint4: {trajectory: 0.1, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
    robot0_joint5: {trajectory: 0.1, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
    robot0_joint6: {trajectory: 0.1, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
    robot0_joint7: {trajectory: 0.1, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
  gains:
    robot0_joint1: {p: 10000, d: 800, i: 0, i_clamp: 1} # {p: 10000, d: 800, i: 0, i_clamp: 1}
    robot0_joint2: {p: 40000, d: 600, i: 0, i_clamp: 1} # {p: 40000, d: 600, i: 0, i_clamp: 1}
    robot0_joint3: {p: 10000, d: 200, i: 0, i_clamp: 1} # {p: 10000, d: 200, i: 0, i_clamp: 1}
    robot0_joint4: {p: 20000, d: 200, i: 50, i_clamp: 1} # {p: 20000, d: 200, i: 50, i_clamp: 1}
    robot0_joint5: {p: 20000, d: 200, i: 50, i_clamp: 1} # {p: 20000, d: 200, i: 50, i_clamp: 1}
    robot0_joint6: {p: 20000, d: 250, i: 0, i_clamp: 1} # {p: 20000, d: 250, i: 0, i_clamp: 1}
    robot0_joint7: {p: 10000, d: 100, i: 0, i_clamp: 1} # {p: 10000, d: 100, i: 0, i_clamp: 1}

  stop_trajectory_duration: 0.5 # 1.0
  state_publish_rate: 50
  action_monitor_rate: 10
  allow_partial_joints_goal: true

panda_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper0_finger_joint1
    - gripper0_finger_joint2
  constraints:
    goal_time: 1.5
    stopped_velocity_tolerance: 0.5
    gripper0_finger_joint1: {trajectory: 0.3, goal: 0.25}
    gripper0_finger_joint2: {trajectory: 0.3, goal: 0.25}
  stop_trajectory_duration: 1.5
  state_publish_rate: 50
  action_monitor_rate: 10
  allow_partial_joints_goal: true
