# MuJoCo ROS control
robot_joints:
  - robot0_shoulder_pan_joint
  - robot0_shoulder_lift_joint
  - robot0_elbow_joint
  - robot0_wrist_1_joint
  - robot0_wrist_2_joint
  - robot0_wrist_3_joint

robot_initial_state:
  # home
  robot0_shoulder_pan_joint: 0.0
  robot0_shoulder_lift_joint: 0.0
  robot0_elbow_joint: 0.0
  robot0_wrist_1_joint: 0.0
  robot0_wrist_2_joint: 0.0
  robot0_wrist_3_joint: 0.0
