ur5_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robot0_shoulder_pan_joint
    - robot0_shoulder_lift_joint
    - robot0_elbow_joint
    - robot0_wrist_1_joint
    - robot0_wrist_2_joint
    - robot0_wrist_3_joint
  gains:
      robot0_shoulder_pan_joint: {p: 4000.0, i: 1000.0, d: 100.0, i_clamp_max: 10.0, i_clamp_min: -10.0}
      robot0_shoulder_lift_joint: {p: 2000.0, i: 500.0, d: 100.0, i_clamp_max: 10.0, i_clamp_min: -10.0}
      robot0_elbow_joint: {p: 1500.0, i: 500.0, d: 50.0, i_clamp_max: 10.0, i_clamp_min: -10.0}
      robot0_wrist_1_joint: {p: 700.0, i: 200.0, d: 10.0, i_clamp: 0.0}
      robot0_wrist_2_joint: {p: 700.0, i: 200.0, d: 10.0, i_clamp: 0.0}
      robot0_wrist_3_joint: {p: 700.0, i: 200.0, d: 10.0, i_clamp: 0.0}
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      robot0_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1}
      robot0_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1}
      robot0_elbow_joint: {trajectory: 0.2, goal: 0.1}
      robot0_wrist_1_joint: {trajectory: 0.2, goal: 0.1}
      robot0_wrist_2_joint: {trajectory: 0.2, goal: 0.1}
      robot0_wrist_3_joint: {trajectory: 0.2, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate: 50
  action_monitor_rate: 10
  # allow_partial_joints_goal: true

# ur5_trajectory_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - rh_FFJ1
#     - rh_FFJ2
#     - rh_FFJ3
#     - rh_FFJ4
#     - rh_LFJ1
#     - rh_LFJ2
#     - rh_LFJ3
#     - rh_LFJ4
#     - rh_LFJ5
#     - rh_MFJ1
#     - rh_MFJ2
#     - rh_MFJ3
#     - rh_MFJ4
#     - rh_RFJ1
#     - rh_RFJ2
#     - rh_RFJ3
#     - rh_RFJ4
#     - rh_THJ1
#     - rh_THJ2
#     - rh_THJ3
#     - rh_THJ4
#     - rh_THJ5
#     - rh_WRJ1
#     - rh_WRJ2
#   constraints:
#       goal_time: 0.6
#       stopped_velocity_tolerance: 10.0
#       rh_FFJ1: {trajectory: 2.0, goal: 2.1}
#       rh_FFJ2: {trajectory: 2.0, goal: 2.1}
#       rh_FFJ3: {trajectory: 2.0, goal: 2.1}
#       rh_FFJ4: {trajectory: 2.0, goal: 2.1}
#       rh_LFJ1: {trajectory: 2.0, goal: 2.1}
#       rh_LFJ2: {trajectory: 2.0, goal: 2.1}
#       rh_LFJ3: {trajectory: 2.0, goal: 2.1}
#       rh_LFJ4: {trajectory: 2.0, goal: 2.1}
#       rh_LFJ5: {trajectory: 2.0, goal: 2.1}
#       rh_MFJ1: {trajectory: 2.0, goal: 2.1}
#       rh_MFJ2: {trajectory: 2.0, goal: 2.1}
#       rh_MFJ3: {trajectory: 2.0, goal: 2.1}
#       rh_MFJ4: {trajectory: 2.0, goal: 2.1}
#       rh_RFJ1: {trajectory: 2.0, goal: 2.1}
#       rh_RFJ2: {trajectory: 2.0, goal: 2.1}
#       rh_RFJ3: {trajectory: 2.0, goal: 2.1}
#       rh_RFJ4: {trajectory: 2.0, goal: 2.1}
#       rh_THJ1: {trajectory: 2.0, goal: 2.1}
#       rh_THJ2: {trajectory: 2.0, goal: 2.1}
#       rh_THJ3: {trajectory: 2.0, goal: 2.1}
#       rh_THJ4: {trajectory: 2.0, goal: 2.1}
#       rh_THJ5: {trajectory: 2.0, goal: 2.1}
#       rh_WRJ1: {trajectory: 2.0, goal: 2.1}
#       rh_WRJ2: {trajectory: 2.0, goal: 2.1}
#   stop_trajectory_duration: 0.5
#   allow_partial_joints_goal: true
#   gains:
#     rh_FFJ1:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_FFJ2:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_FFJ3:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_FFJ4:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_LFJ1:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_LFJ2:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_LFJ3:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_LFJ4:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_LFJ5:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_MFJ1:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_MFJ2:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_MFJ3:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_MFJ4:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_RFJ1:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_RFJ2:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_RFJ3:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_RFJ4:
#       p: 4.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_THJ1:
#       p: 4.0
#       i: 0.0
#       d: 0.2
#       i_clamp: 0.0
#       antiwindup: true
#     rh_THJ2:
#       p: 4.0
#       i: 0.0
#       d: 0.2
#       i_clamp: 0.0
#       antiwindup: true
#     rh_THJ3:
#       p: 4.0
#       i: 0.0
#       d: 0.2
#       i_clamp: 0.0
#       antiwindup: true
#     rh_THJ4:
#       p: 4.0
#       i: 0.0
#       d: 0.2
#       i_clamp: 0.0
#       antiwindup: true
#     rh_THJ5:
#       p: 4.0
#       i: 0.0
#       d: 0.2
#       i_clamp: 0.0
#       antiwindup: true
#     rh_WRJ1:
#       p: 10.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
#     rh_WRJ2:
#       p: 8.0
#       i: 0.0
#       d: 0.1
#       i_clamp: 0.0
#       antiwindup: true
