# controller_list:
#   - name: ""
#     action_ns: follow_joint_trajectory
#     type: FollowJointTrajectory
#     joints:
#       - robot0_shoulder_pan_joint
#       - robot0_shoulder_lift_joint
#       - robot0_elbow_joint
#       - robot0_wrist_1_joint
#       - robot0_wrist_2_joint
#       - robot0_wrist_3_joint

ur5e_robotiq_3f_manipulator_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - robot0_shoulder_pan_joint
    - robot0_shoulder_lift_joint
    - robot0_elbow_joint
    - robot0_wrist_1_joint
    - robot0_wrist_2_joint
    - robot0_wrist_3_joint
  constraints:
      goal_time: 1.5 # 0.6
      stopped_velocity_tolerance: 0.5 # 0.05
      robot0_shoulder_pan_joint: {trajectory: 0.3, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
      robot0_shoulder_lift_joint: {trajectory: 0.3, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
      robot0_elbow_joint: {trajectory: 0.3, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
      robot0_wrist_1_joint: {trajectory: 0.3, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
      robot0_wrist_2_joint: {trajectory: 0.3, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
      robot0_wrist_3_joint: {trajectory: 0.3, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
  stop_trajectory_duration: 2.0 # 1.0
  state_publish_rate: 50
  action_monitor_rate: 10
  allow_partial_joints_goal: true

# ur5e_robotiq_2f_85_manipulator_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - robot0_shoulder_pan_joint
#     - robot0_shoulder_lift_joint
#     - robot0_elbow_joint
#     - robot0_wrist_1_joint
#     - robot0_wrist_2_joint
#     - robot0_wrist_3_joint
#   constraints:
#       goal_time: 0.6
#       stopped_velocity_tolerance: 0.05
#       robot0_shoulder_pan_joint: {trajectory: 0.2, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
#       robot0_shoulder_lift_joint: {trajectory: 0.2, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
#       robot0_elbow_joint: {trajectory: 0.2, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
#       robot0_wrist_1_joint: {trajectory: 0.2, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
#       robot0_wrist_2_joint: {trajectory: 0.2, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
#       robot0_wrist_3_joint: {trajectory: 0.2, goal: 0.1} # {trajectory: 0.2, goal: 0.1}
#   stop_trajectory_duration: 1.0
#   state_publish_rate: 50
#   action_monitor_rate: 10
#   allow_partial_joints_goal: true

# ra_trajectory_controller:
#   type: "position_controllers/JointTrajectoryController"
#   joints:
#     - ra_shoulder_pan_joint
#     - ra_shoulder_lift_joint
#     - ra_elbow_joint
#     - ra_wrist_1_joint
#     - ra_wrist_2_joint
#     - ra_wrist_3_joint
#   constraints:
#       goal_time: 0.6
#       stopped_velocity_tolerance: 1.0
#       ra_shoulder_pan_joint: {trajectory: 0.3, goal: 0.1}
#       ra_shoulder_lift_joint: {trajectory: 0.3, goal: 0.1}
#       ra_elbow_joint: {trajectory: 0.3, goal: 0.1}
#       ra_wrist_1_joint: {trajectory: 0.3, goal: 0.1}
#       ra_wrist_2_joint: {trajectory: 0.3, goal: 0.1}
#       ra_wrist_3_joint: {trajectory: 0.3, goal: 0.1}
#   stop_trajectory_duration: 0.5
#   state_publish_rate:  25
#   action_monitor_rate: 10
#   allow_partial_joints_goal: true

# gripper controller
# ur5e_robotiq_2f_85_gripper_controller:
#   type: position_controllers/GripperActionController
#   joint: gripper0_finger_joint

ur5e_robotiq_3f_gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper0_finger_1_joint_1
    - gripper0_finger_2_joint_1
    - gripper0_finger_middle_joint_1
    - gripper0_palm_finger_1_joint
  constraints:
      goal_time: 1.5
      stopped_velocity_tolerance: 0.5
      gripper0_finger_1_joint_1: {trajectory: 0.2, goal: 0.1}
      gripper0_finger_2_joint_1: {trajectory: 0.2, goal: 0.1}
      gripper0_finger_middle_joint_1: {trajectory: 0.2, goal: 0.1}
      gripper0_palm_finger_1_joint: {trajectory: 0.2, goal: 0.1}
  stop_trajectory_duration: 1.5
  state_publish_rate: 50
  action_monitor_rate: 10
  allow_partial_joints_goal: true

# ur5e_robotiq_3f_gripper_controller:
#   type: position_controllers/JointTrajectoryController
#   joints:
#     - gripper0_finger_1_joint_1
#     - gripper0_finger_2_joint_1
#     - gripper0_finger_middle_joint_1
#     - gripper0_palm_finger_1_joint
#   constraints:
#       goal_time: 1.5
#       stopped_velocity_tolerance: 0.5
#       gripper0_finger_1_joint_1: {trajectory: 0.4, goal: 0.5}
#       gripper0_finger_2_joint_1: {trajectory: 0.4, goal: 0.5}
#       gripper0_finger_middle_joint_1: {trajectory: 0.4, goal: 0.5}
#       gripper0_palm_finger_1_joint: {trajectory: 0.4, goal: 0.5}
#   stop_trajectory_duration: 1.5
#   state_publish_rate: 50
#   action_monitor_rate: 10
#   allow_partial_joints_goal: true
